services:
  database:
    image: mcr.microsoft.com/azure-sql-edge
    container_name: mssql_server
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Dinosaurio233@" # Â¡Cambia esto por uno tuyo!
    volumes:
      - ./sqldata:/var/opt/mssql/data